pipeline {
    agent {
         docker { image 'maven:3.8.6-adoptopenjdk-11' }
    }
    stages {
        stage('Build') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
