pipeline {
    agent {
        docker {
            image 'node:8'
        }
    }
    stages {
        stage('Test') {
            steps {
                dir('sample-node-project') {
                    sh 'node --version'
                }
            }
        }
        stage('Npm Install') {
            steps {
                dir('sample-node-project') {
                    sh 'npm install'
                }
            }
        }
        stage('Fix Permissions') {
            steps {
                sh 'sudo chown -R 115:122 /.npm'
            }
        }
        stage('Npm Start') {
            steps {
                dir('sample-node-project') {
                    sh 'npm start &'
                }
            }
        }
    }
}
