pipeline {
    agent {
        docker {
            image 'node:16-alpine'
           // user 'node'  // Set the user to 'node' inside the Docker container
        }
    }
    stages {
        stage('Test') {
            steps {
                dir('Login_Express_App') {
                    sh 'node --version'
                }
            }
        }
        stage('Npm install') {
            steps {
                dir('Login_Express_App') {
                    sh 'npm install --unsafe-perm'  // Use '--unsafe-perm' to avoid permission issues
                }
            }
        }
        stage('Npm Start') {
            steps {
                dir('Login_Express_App') {
                    sh 'npm start &'
                }
            }
        }
    }
}
