pipeline {
    agent {
        docker { 
            image 'node:16-alpine' 
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
        stage('Npm Install') {
            steps {
                dir('node-express-hello-world') { 
                    sh 'npm install'
                }
            }
        }
        stage('Npm Start') {
            steps {
                dir('node-express-hello-world') { 
                    sh 'npm start' 
                }
            }
        }
    }
}
