pipeline {
    agent {
        docker { 
            image 'node:18-alpine' 
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
		  stage('Change Ownership') {
            steps {
                sh "chown -R 115:122 ${WORKSPACE}/.npm"
            }
        }
        stage('Npm Install') {
            steps {
                dir('node-express-hello-world') { 
                    sh 'npm install'
                }
            }
        }
        stage('Npm Start') {
            steps {
                dir('node-express-hello-world') { 
                    sh 'npm start' 
                }
            }
        }
    }
}
