pipeline {
    agent {
        docker {
            image 'node:16-alpine'
        }
    }
    stages {
        stage('Test') {
            steps {
                dir('node-hello') {
                    sh 'node --version'
                }
            }
        }
        stage('Npm Start') {
            steps {
                dir('node-hello') {
                    sh 'npm start'
                }
            }
        }
    }
}
